info = {
    id = "00_nozzle_clean",
    type = "project.plugin",
    title = "Nozzle clean: which maintenance file to run from the USB stick before testing",
    menu = "Filament Dial-In/0. Nozzle clean before testing",
    params = {
        { name = "routine", label = "Routine: cold_pull_nylon (default), cold_pull_pla, hot_flush, flow_test, nozzle_brush (the last four: MK4S only)", type = "string", default = "cold_pull_nylon" },
        { name = "high_flow", label = "High Flow / CHT nozzle (longer soak, bigger purge; the file warns if the printer's Nozzle Type is Standard)", type = "bool", default = false },
        { name = "tag", label = "Printer tag for the sheet (blank = from profile.lua or the printer name)", type = "string", default = "" },
    },
}

-- Step 0, before any measurement: a nozzle that still holds the last
-- material's residue drags it into every test print.
--
-- The cleaning is not done inside a sliced print any more. The bundle ships
-- Prusa-firmware maintenance files (assets/nozzle/<PRINTER>/*.bgcode, with the
-- same sequences as plain .gcode beside them) that home, park high at the bed
-- centre, heat, purge, cool with the fan and do the extruder-driven cold pull
-- with the printer's own prompts, thumbnail and progress bar. They are run
-- from the USB stick like any other print. This command adds nothing to the
-- plate: it works out which file matches the selected printer and nozzle,
-- says where it is, and tells the sheet.
--
-- The files were generated by tools/nozzle-suite/generator/make_suite.py
-- against the Prusa-Firmware-Buddy source; see assets/nozzle/README.txt.

local PRINTERS = {
    -- pattern (on the lowercased printer name), folder, display name.
    -- Longer names first, so "core one l" is not taken for "core one".
    { "core one l%f[%A]", "COREONEL", "CORE One L / L+" },
    { "core one", "COREONE", "CORE One / One+ / One+ (Gen 2)" },
    { "mk4s", "MK4S", "MK4S" },
}

-- file: %s is the folder name; nozzle: true when STD/HF variants exist.
local ROUTINES = {
    cold_pull_nylon = { file = "%s_01_cold_pull_nylon", nozzle = true, all = true,
        what = "nylon purge at 290 C, fan cool-down, extruder-driven cold pull at 145 C" },
    cold_pull_pla = { file = "%s_02_cold_pull_pla", nozzle = false,
        what = "the firmware's own Cold Pull numbers with PLA (pull 90 C, hold 95 C)" },
    hot_flush = { file = "%s_03_hot_flush", nozzle = true,
        what = "290 C push-through with ram-back cycles, nylon or cleaning filament" },
    flow_test = { file = "%s_04_flow_test", nozzle = true,
        what = "PLA at 220 C, stepped speeds with prompts; watch for clicking or thinning" },
    nozzle_brush = { file = "%s_05_nozzle_brush", nozzle = false,
        what = "heat to 250 C, park front and high, hold for a brass-brush clean" },
}
local ROUTINE_ORDER = { "cold_pull_nylon", "cold_pull_pla", "hot_flush", "flow_test", "nozzle_brush" }

local function detect(name)
    local lower = name:lower()
    for _, p in ipairs(PRINTERS) do
        if lower:find(p[1]) then
            return p[2], p[3]
        end
    end
    return nil
end

function execute(opts)
    local util = require("lib/util")

    local routine_key = tostring(opts.routine or ""):lower():gsub("[%s%-]", "_")
    if routine_key == "" then routine_key = "cold_pull_nylon" end
    local routine = ROUTINES[routine_key]
    assert(routine, "Routine must be one of " .. table.concat(ROUTINE_ORDER, ", "))
    local high_flow = opts.high_flow and true or false

    local bed = api.project:current_bed()
    local name = util.printer_name(bed)
    local tag = util.resolve_tag(bed, opts.tag)
    local folder, family = detect(name)
    if not folder then
        local supported = {}
        for _, p in ipairs(PRINTERS) do supported[#supported + 1] = p[3] end
        error("No nozzle maintenance file for printer '" .. name .. "'. Files ship for " .. table.concat(supported, "; ")
            .. ". For other printers use the printer's own cold-pull routine, or adapt the MK4S sequence with tools/nozzle-suite/generator/make_suite.py.")
    end
    if not routine.all and folder ~= "MK4S" then
        error("Routine " .. routine_key .. " exists only for the MK4S; the " .. family .. " ships cold_pull_nylon.")
    end

    local base = string.format(routine.file, folder)
    if routine.nozzle then
        base = base .. (high_flow and "_HF" or "_STD")
    end
    local rel = "assets/nozzle/" .. folder .. "/" .. base
    local file, plain = rel .. ".bgcode", rel .. ".gcode"

    util.log(string.format("nozzle clean for %s (%s, %s nozzle): run %s from the USB stick", tag, family, high_flow and "High Flow" or "standard", base .. ".bgcode"))
    util.log("the file is in the plugin bundle: <PrusaSlicer user folder>/plugins/com.ripleydynamics.filament-dialin/" .. file .. " (the sheet offers it as a download; the same sequence as plain G-code is " .. base .. ".gcode)")
    util.log("routine: " .. routine.what)
    util.log("before the run: load the filament the prompt names, put a scrap of paper on the bed under the nozzle, watch the first run; the prompts say Continue, the printer's button says Resume")
    util.log("a suspected clog (MK4S): flow_test, hot_flush, flow_test, cold_pull_nylon, flow_test; do not use a needle on a High Flow / CHT nozzle")
    util.log("nothing was added to the plate; this step prints from the USB stick, not from PrusaSlicer")
    util.data(bed, "clean", { tag = tag, routine = routine_key, high_flow = high_flow, printer_model = folder, family = family,
        file = file, plain = plain, method = "usb" })
end
